version: '3.8'

services:

  datingappdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  pgadminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080